# PROJECTS DIRECTORY
# Absolute path to the folder where your projects are stored.
projects: E:/Dropbox/Development/generate


# ASSEMBLE PATHS
# ==============

# assemble
assemble_master: <%= config.projects %>/assemble/assemble-master
assemble_gh: <%= config.projects %>/assemble/assemble-gh
assemble_wiki: <%= config.projects %>/assemble/assemble-wiki

# helper-lib
helpers: <%= config.projects %>/assemble/helpers

# assemble-less
less: <%= config.projects %>/assemble/assemble-less/master
less_gh: <%= config.projects %>/assemble/assemble-less/gh-pages

# assemble-less-tests
less_tests: <%= config.projects %>/assemble/assemble-less/less-tests
less_tests_gh: <%= config.projects %>/assemble/assemble-less/less-tests-gh

# assemble-manifest
manifest: <%= config.projects %>/assemble/assemble-manifest

# assemble-utils
utils: <%= config.projects %>/assemble/assemble-utils

# assemble-examples
examples: <%= config.projects %>/assemble/assemble-examples

# task-manifest
task_manifest: <%= config.projects %>/assemble/task-manifest



# UPSTAGE PATHS
# =============

# upstage
upstage: <%= config.projects %>/upstage
upstage_gh: <%= config.projects %>/upstage
upstage_wiki: <%= config.projects %>/upstage

app: <%= config.projects %>/upstage/app/upstage-master

